language: cpp

dist: focal

#cache:
#  directories:
#    - /home/travis/.conan

## FIXME : This the cache generate this error
## opengl/system: Already installed!
## ERROR: opengl/system: Error in package_info() method, line 78
##  self._fill_cppinfo_from_pkgconfig('gl')
## while calling '_fill_cppinfo_from_pkgconfig', line 21
##  if not pkg_config.provides:
##  ConanException: pkg-config command ['pkg-config', '--print-provides', 'gl', '--print-errors'] failed with error: Command 'pkg-config --print-provides gl --print-errors' returned non-zero exit status 1.

matrix:
  include:
    - name: "Linux (GCC compiler)"
      os: linux
      compiler: gcc
      env: OS=linux COMPILER=gcc GCC_VERSION=10 CODECOV_TOKEN="30f26de8-86d2-4287-82de-3b14d6ee60fb"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-10
            - g++-10
            - cmake
            - python3
            - python3-pip
            - python3-setuptools
            - lcov
          update: true
      after_script:
        - bash <(curl -s https://codecov.io/bash)

#    - name: "Linux (Clang compiler)"
#      os: linux
#      compiler: clang
#      env: OS=linux COMPILER=clang CLANG_VERSION=11
#      addons:
#        apt:
#          sources:
#            - sourceline: 'ppa:ubuntu-toolchain-r/test'
#          packages:
#            - clang-11
#            - cmake
#            - python3
#            - python3-pip
#            - python3-setuptools
#            - lcov
#          update: true

#    - name: "MacOS"
#      os: osx
#      compiler: clang
#      env: OS=osx COMPILER=clang
#      osx_image: xcode12.2

before_install:
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "gcc" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  - if [ "$OS" == "osx" ]; then brew update; fi
  - cmake --version
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple

install:
  - ./tools/install.sh
  - conan --version
  - cmake --version

script:
  - ./tools/generate.sh -- -DENABLE_COVERAGE:BOOL=TRUE -DENABLE_TESTING:BOOL=TRUE
  - ./tools/build.sh --test

notifications:
  email:
    on_success: never
