name: C++ CMake Build

on:
#  push:
#    branches-ignore:
#      - 'doc/**'
#      - 'tmp/**'
#      - 'experimental/**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
#          macos-latest,
          windows-latest
        ]
        build_type: [
          "MinSizeRel",
#          "Release"
#          "RelWithDebInfo",
          "Debug"
        ]
        arch: [
#          "x32",
          "x64"
        ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

# https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: ${{ matrix.arch }}

      - name: Installing Dependencies
        shell: bash
        run: ./tools/install.sh

## FIXME : This step generate this error
## opengl/system: Already installed!
## ERROR: opengl/system: Error in package_info() method, line 78
##  self._fill_cppinfo_from_pkgconfig('gl')
## while calling '_fill_cppinfo_from_pkgconfig', line 21
##  if not pkg_config.provides:
##  ConanException: pkg-config command ['pkg-config', '--print-provides', 'gl', '--print-errors'] failed with error: Command 'pkg-config --print-provides gl --print-errors' returned non-zero exit status 1.

## https://github.com/marketplace/actions/cache
##      - name: Conan Cache
##        uses: actions/cache@v2
##        with:
##          path: ~/.conan
##          key: conan-cache-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.build_type }}-${{ hashFiles('**/conanfile.txt') }}

      - name: Generate
        shell: bash
        run: ./tools/generate.sh --build_type ${{ matrix.build_type }} --arch ${{ matrix.arch }}

      - name: Build
        shell: bash
        run: ./tools/build.sh --build_type ${{ matrix.build_type }} --arch ${{ matrix.arch }}

      - name: Launch
        shell: bash
        run: ./tools/launch.sh --build_type ${{ matrix.build_type }} --arch ${{ matrix.arch }} -- --version

## FIXME : Not launching on ubuntu because it cause this error : https://github.com/Mathieu-Lala/game_project/runs/1318788094?check_suite_focus=true
## ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
## ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
## ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
## ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
## ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
## ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
## ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
## ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

      # TODO :
        # add steps 'unit-tests'
        # add steps 'fuzz'
        # add steps 'golden-tests'
        # add steps 'benchmark'
        # add steps 'style & lint'
        # ..
